[package]
name = "kinton-hub"
version = "0.1.0"
authors = ["Diego Fernández Barrera <bigomby@gmail.com>"]

[dependencies]
hyper = "0.9"
yup-hyper-mock = "*"
mqttc = "0.1.4"
netopt = "0.1.3"
httparse = "1.2.0"
json = "*"
lazy_static = "0.1.*"
log = "*"
